/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Token = IDL.Text;
export const Result = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const ArticleInput = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishDate' : IDL.Text,
  'coverImage' : IDL.Text,
  'pdfUrl' : IDL.Opt(IDL.Text),
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});
export const NoteInput = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishDate' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'pdfUrl' : IDL.Opt(IDL.Text),
  'excerpt' : IDL.Text,
});
export const PublicationInput = IDL.Record({
  'title' : IDL.Text,
  'venue' : IDL.Text,
  'link' : IDL.Text,
  'year' : IDL.Nat,
  'authors' : IDL.Vec(IDL.Text),
  'pubType' : IDL.Text,
  'pdfUrl' : IDL.Opt(IDL.Text),
});
export const ResearchInput = IDL.Record({
  'title' : IDL.Text,
  'fullContent' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'seqNum' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'pdfUrl' : IDL.Opt(IDL.Text),
});
export const ContactRecord = IDL.Record({
  'id' : IDL.Nat,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const StatItem = IDL.Record({
  'value' : IDL.Text,
  'statLabel' : IDL.Text,
});
export const Milestone = IDL.Record({
  'title' : IDL.Text,
  'year' : IDL.Nat,
  'description' : IDL.Text,
});
export const ProfileInput = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'stats' : IDL.Vec(StatItem),
  'avatarUrl' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
  'milestones' : IDL.Vec(Milestone),
});
export const Article = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishDate' : IDL.Text,
  'coverImage' : IDL.Text,
  'pdfUrl' : IDL.Opt(IDL.Text),
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});
export const Note = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishDate' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'pdfUrl' : IDL.Opt(IDL.Text),
  'excerpt' : IDL.Text,
});
export const Profile = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'stats' : IDL.Vec(StatItem),
  'avatarUrl' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
  'milestones' : IDL.Vec(Milestone),
});
export const Publication = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'venue' : IDL.Text,
  'link' : IDL.Text,
  'year' : IDL.Nat,
  'authors' : IDL.Vec(IDL.Text),
  'pubType' : IDL.Text,
  'pdfUrl' : IDL.Opt(IDL.Text),
});
export const ResearchProject = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'fullContent' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'seqNum' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'pdfUrl' : IDL.Opt(IDL.Text),
});
export const ContactSubmission = IDL.Record({
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  'adminChangePassword' : IDL.Func([Token, IDL.Text], [Result], []),
  'adminCreateArticle' : IDL.Func([Token, ArticleInput], [Result], []),
  'adminCreateNote' : IDL.Func([Token, NoteInput], [Result], []),
  'adminCreatePublication' : IDL.Func([Token, PublicationInput], [Result], []),
  'adminCreateResearch' : IDL.Func([Token, ResearchInput], [Result], []),
  'adminDeleteArticle' : IDL.Func([Token, IDL.Nat], [Result], []),
  'adminDeleteNote' : IDL.Func([Token, IDL.Nat], [Result], []),
  'adminDeletePublication' : IDL.Func([Token, IDL.Nat], [Result], []),
  'adminDeleteResearch' : IDL.Func([Token, IDL.Nat], [Result], []),
  'adminGetContacts' : IDL.Func(
      [Token],
      [IDL.Variant({ 'ok' : IDL.Vec(ContactRecord), 'err' : IDL.Text })],
      [],
    ),
  'adminLogin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : Token, 'err' : IDL.Text })],
      [],
    ),
  'adminLogout' : IDL.Func([Token], [Result], []),
  'adminUpdateArticle' : IDL.Func([Token, IDL.Nat, ArticleInput], [Result], []),
  'adminUpdateNote' : IDL.Func([Token, IDL.Nat, NoteInput], [Result], []),
  'adminUpdateProfile' : IDL.Func([Token, ProfileInput], [Result], []),
  'adminUpdatePublication' : IDL.Func(
      [Token, IDL.Nat, PublicationInput],
      [Result],
      [],
    ),
  'adminUpdateResearch' : IDL.Func(
      [Token, IDL.Nat, ResearchInput],
      [Result],
      [],
    ),
  'adminValidateToken' : IDL.Func([Token], [IDL.Bool], ['query']),
  'getArticle' : IDL.Func([IDL.Nat], [IDL.Opt(Article)], ['query']),
  'getArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getNote' : IDL.Func([IDL.Nat], [IDL.Opt(Note)], ['query']),
  'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getPublication' : IDL.Func([IDL.Nat], [IDL.Opt(Publication)], ['query']),
  'getPublications' : IDL.Func([], [IDL.Vec(Publication)], ['query']),
  'getResearchProject' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ResearchProject)],
      ['query'],
    ),
  'getResearchProjects' : IDL.Func([], [IDL.Vec(ResearchProject)], ['query']),
  'submitContact' : IDL.Func([ContactSubmission], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Token = IDL.Text;
  const Result = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const ArticleInput = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishDate' : IDL.Text,
    'coverImage' : IDL.Text,
    'pdfUrl' : IDL.Opt(IDL.Text),
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  const NoteInput = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishDate' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'pdfUrl' : IDL.Opt(IDL.Text),
    'excerpt' : IDL.Text,
  });
  const PublicationInput = IDL.Record({
    'title' : IDL.Text,
    'venue' : IDL.Text,
    'link' : IDL.Text,
    'year' : IDL.Nat,
    'authors' : IDL.Vec(IDL.Text),
    'pubType' : IDL.Text,
    'pdfUrl' : IDL.Opt(IDL.Text),
  });
  const ResearchInput = IDL.Record({
    'title' : IDL.Text,
    'fullContent' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'seqNum' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'pdfUrl' : IDL.Opt(IDL.Text),
  });
  const ContactRecord = IDL.Record({
    'id' : IDL.Nat,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const StatItem = IDL.Record({ 'value' : IDL.Text, 'statLabel' : IDL.Text });
  const Milestone = IDL.Record({
    'title' : IDL.Text,
    'year' : IDL.Nat,
    'description' : IDL.Text,
  });
  const ProfileInput = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'stats' : IDL.Vec(StatItem),
    'avatarUrl' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
    'milestones' : IDL.Vec(Milestone),
  });
  const Article = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishDate' : IDL.Text,
    'coverImage' : IDL.Text,
    'pdfUrl' : IDL.Opt(IDL.Text),
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  const Note = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishDate' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'pdfUrl' : IDL.Opt(IDL.Text),
    'excerpt' : IDL.Text,
  });
  const Profile = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'stats' : IDL.Vec(StatItem),
    'avatarUrl' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
    'milestones' : IDL.Vec(Milestone),
  });
  const Publication = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'venue' : IDL.Text,
    'link' : IDL.Text,
    'year' : IDL.Nat,
    'authors' : IDL.Vec(IDL.Text),
    'pubType' : IDL.Text,
    'pdfUrl' : IDL.Opt(IDL.Text),
  });
  const ResearchProject = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'fullContent' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'seqNum' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'pdfUrl' : IDL.Opt(IDL.Text),
  });
  const ContactSubmission = IDL.Record({
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    'adminChangePassword' : IDL.Func([Token, IDL.Text], [Result], []),
    'adminCreateArticle' : IDL.Func([Token, ArticleInput], [Result], []),
    'adminCreateNote' : IDL.Func([Token, NoteInput], [Result], []),
    'adminCreatePublication' : IDL.Func(
        [Token, PublicationInput],
        [Result],
        [],
      ),
    'adminCreateResearch' : IDL.Func([Token, ResearchInput], [Result], []),
    'adminDeleteArticle' : IDL.Func([Token, IDL.Nat], [Result], []),
    'adminDeleteNote' : IDL.Func([Token, IDL.Nat], [Result], []),
    'adminDeletePublication' : IDL.Func([Token, IDL.Nat], [Result], []),
    'adminDeleteResearch' : IDL.Func([Token, IDL.Nat], [Result], []),
    'adminGetContacts' : IDL.Func(
        [Token],
        [IDL.Variant({ 'ok' : IDL.Vec(ContactRecord), 'err' : IDL.Text })],
        [],
      ),
    'adminLogin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : Token, 'err' : IDL.Text })],
        [],
      ),
    'adminLogout' : IDL.Func([Token], [Result], []),
    'adminUpdateArticle' : IDL.Func(
        [Token, IDL.Nat, ArticleInput],
        [Result],
        [],
      ),
    'adminUpdateNote' : IDL.Func([Token, IDL.Nat, NoteInput], [Result], []),
    'adminUpdateProfile' : IDL.Func([Token, ProfileInput], [Result], []),
    'adminUpdatePublication' : IDL.Func(
        [Token, IDL.Nat, PublicationInput],
        [Result],
        [],
      ),
    'adminUpdateResearch' : IDL.Func(
        [Token, IDL.Nat, ResearchInput],
        [Result],
        [],
      ),
    'adminValidateToken' : IDL.Func([Token], [IDL.Bool], ['query']),
    'getArticle' : IDL.Func([IDL.Nat], [IDL.Opt(Article)], ['query']),
    'getArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getNote' : IDL.Func([IDL.Nat], [IDL.Opt(Note)], ['query']),
    'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getPublication' : IDL.Func([IDL.Nat], [IDL.Opt(Publication)], ['query']),
    'getPublications' : IDL.Func([], [IDL.Vec(Publication)], ['query']),
    'getResearchProject' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ResearchProject)],
        ['query'],
      ),
    'getResearchProjects' : IDL.Func([], [IDL.Vec(ResearchProject)], ['query']),
    'submitContact' : IDL.Func([ContactSubmission], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };