/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Article {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'publishDate' : string,
  'coverImage' : string,
  'pdfUrl' : [] | [string],
  'excerpt' : string,
  'category' : string,
}
export interface ArticleInput {
  'title' : string,
  'content' : string,
  'publishDate' : string,
  'coverImage' : string,
  'pdfUrl' : [] | [string],
  'excerpt' : string,
  'category' : string,
}
export interface ContactRecord {
  'id' : bigint,
  'subject' : string,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'message' : string,
}
export interface ContactSubmission {
  'subject' : string,
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface Milestone {
  'title' : string,
  'year' : bigint,
  'description' : string,
}
export interface Note {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'publishDate' : string,
  'tags' : Array<string>,
  'pdfUrl' : [] | [string],
  'excerpt' : string,
}
export interface NoteInput {
  'title' : string,
  'content' : string,
  'publishDate' : string,
  'tags' : Array<string>,
  'pdfUrl' : [] | [string],
  'excerpt' : string,
}
export interface Profile {
  'bio' : string,
  'name' : string,
  'stats' : Array<StatItem>,
  'avatarUrl' : string,
  'skills' : Array<string>,
  'milestones' : Array<Milestone>,
}
export interface ProfileInput {
  'bio' : string,
  'name' : string,
  'stats' : Array<StatItem>,
  'avatarUrl' : string,
  'skills' : Array<string>,
  'milestones' : Array<Milestone>,
}
export interface Publication {
  'id' : bigint,
  'title' : string,
  'venue' : string,
  'link' : string,
  'year' : bigint,
  'authors' : Array<string>,
  'pubType' : string,
  'pdfUrl' : [] | [string],
}
export interface PublicationInput {
  'title' : string,
  'venue' : string,
  'link' : string,
  'year' : bigint,
  'authors' : Array<string>,
  'pubType' : string,
  'pdfUrl' : [] | [string],
}
export interface ResearchInput {
  'title' : string,
  'fullContent' : string,
  'tags' : Array<string>,
  'description' : string,
  'seqNum' : bigint,
  'imageUrl' : string,
  'pdfUrl' : [] | [string],
}
export interface ResearchProject {
  'id' : bigint,
  'title' : string,
  'fullContent' : string,
  'tags' : Array<string>,
  'description' : string,
  'seqNum' : bigint,
  'imageUrl' : string,
  'pdfUrl' : [] | [string],
}
export type Result = { 'ok' : string } |
  { 'err' : string };
export interface StatItem { 'value' : string, 'statLabel' : string }
export type Token = string;
export interface _SERVICE {
  'adminChangePassword' : ActorMethod<[Token, string], Result>,
  'adminCreateArticle' : ActorMethod<[Token, ArticleInput], Result>,
  'adminCreateNote' : ActorMethod<[Token, NoteInput], Result>,
  'adminCreatePublication' : ActorMethod<[Token, PublicationInput], Result>,
  'adminCreateResearch' : ActorMethod<[Token, ResearchInput], Result>,
  'adminDeleteArticle' : ActorMethod<[Token, bigint], Result>,
  'adminDeleteNote' : ActorMethod<[Token, bigint], Result>,
  'adminDeletePublication' : ActorMethod<[Token, bigint], Result>,
  'adminDeleteResearch' : ActorMethod<[Token, bigint], Result>,
  'adminGetContacts' : ActorMethod<
    [Token],
    { 'ok' : Array<ContactRecord> } |
      { 'err' : string }
  >,
  'adminLogin' : ActorMethod<
    [string, string],
    { 'ok' : Token } |
      { 'err' : string }
  >,
  'adminLogout' : ActorMethod<[Token], Result>,
  'adminUpdateArticle' : ActorMethod<[Token, bigint, ArticleInput], Result>,
  'adminUpdateNote' : ActorMethod<[Token, bigint, NoteInput], Result>,
  'adminUpdateProfile' : ActorMethod<[Token, ProfileInput], Result>,
  'adminUpdatePublication' : ActorMethod<
    [Token, bigint, PublicationInput],
    Result
  >,
  'adminUpdateResearch' : ActorMethod<[Token, bigint, ResearchInput], Result>,
  'adminValidateToken' : ActorMethod<[Token], boolean>,
  'getArticle' : ActorMethod<[bigint], [] | [Article]>,
  'getArticles' : ActorMethod<[], Array<Article>>,
  'getNote' : ActorMethod<[bigint], [] | [Note]>,
  'getNotes' : ActorMethod<[], Array<Note>>,
  'getProfile' : ActorMethod<[], [] | [Profile]>,
  'getPublication' : ActorMethod<[bigint], [] | [Publication]>,
  'getPublications' : ActorMethod<[], Array<Publication>>,
  'getResearchProject' : ActorMethod<[bigint], [] | [ResearchProject]>,
  'getResearchProjects' : ActorMethod<[], Array<ResearchProject>>,
  'submitContact' : ActorMethod<[ContactSubmission], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];