/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Article {
    id: bigint;
    title: string;
    content: string;
    publishDate: string;
    coverImage: string;
    pdfUrl?: string;
    excerpt: string;
    category: string;
}
export interface PublicationInput {
    title: string;
    venue: string;
    link: string;
    year: bigint;
    authors: Array<string>;
    pubType: string;
    pdfUrl?: string;
}
export interface ContactSubmission {
    subject: string;
    name: string;
    email: string;
    message: string;
}
export interface ContactRecord {
    id: bigint;
    subject: string;
    name: string;
    createdAt: bigint;
    email: string;
    message: string;
}
export interface Profile {
    bio: string;
    name: string;
    stats: Array<StatItem>;
    avatarUrl: string;
    skills: Array<string>;
    milestones: Array<Milestone>;
}
export interface Milestone {
    title: string;
    year: bigint;
    description: string;
}
export type Result = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface ResearchProject {
    id: bigint;
    title: string;
    fullContent: string;
    tags: Array<string>;
    description: string;
    seqNum: bigint;
    imageUrl: string;
    pdfUrl?: string;
}
export interface StatItem {
    value: string;
    statLabel: string;
}
export interface NoteInput {
    title: string;
    content: string;
    publishDate: string;
    tags: Array<string>;
    pdfUrl?: string;
    excerpt: string;
}
export type Token = string;
export interface Publication {
    id: bigint;
    title: string;
    venue: string;
    link: string;
    year: bigint;
    authors: Array<string>;
    pubType: string;
    pdfUrl?: string;
}
export interface ArticleInput {
    title: string;
    content: string;
    publishDate: string;
    coverImage: string;
    pdfUrl?: string;
    excerpt: string;
    category: string;
}
export interface ProfileInput {
    bio: string;
    name: string;
    stats: Array<StatItem>;
    avatarUrl: string;
    skills: Array<string>;
    milestones: Array<Milestone>;
}
export interface ResearchInput {
    title: string;
    fullContent: string;
    tags: Array<string>;
    description: string;
    seqNum: bigint;
    imageUrl: string;
    pdfUrl?: string;
}
export interface Note {
    id: bigint;
    title: string;
    content: string;
    publishDate: string;
    tags: Array<string>;
    pdfUrl?: string;
    excerpt: string;
}
export interface backendInterface {
    adminChangePassword(token: Token, newPassword: string): Promise<Result>;
    adminCreateArticle(token: Token, input: ArticleInput): Promise<Result>;
    adminCreateNote(token: Token, input: NoteInput): Promise<Result>;
    adminCreatePublication(token: Token, input: PublicationInput): Promise<Result>;
    adminCreateResearch(token: Token, input: ResearchInput): Promise<Result>;
    adminDeleteArticle(token: Token, id: bigint): Promise<Result>;
    adminDeleteNote(token: Token, id: bigint): Promise<Result>;
    adminDeletePublication(token: Token, id: bigint): Promise<Result>;
    adminDeleteResearch(token: Token, id: bigint): Promise<Result>;
    adminGetContacts(token: Token): Promise<{
        __kind__: "ok";
        ok: Array<ContactRecord>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminLogin(adminId: string, password: string): Promise<{
        __kind__: "ok";
        ok: Token;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminLogout(token: Token): Promise<Result>;
    adminUpdateArticle(token: Token, id: bigint, input: ArticleInput): Promise<Result>;
    adminUpdateNote(token: Token, id: bigint, input: NoteInput): Promise<Result>;
    adminUpdateProfile(token: Token, input: ProfileInput): Promise<Result>;
    adminUpdatePublication(token: Token, id: bigint, input: PublicationInput): Promise<Result>;
    adminUpdateResearch(token: Token, id: bigint, input: ResearchInput): Promise<Result>;
    adminValidateToken(token: Token): Promise<boolean>;
    getArticle(id: bigint): Promise<Article | null>;
    getArticles(): Promise<Array<Article>>;
    getNote(id: bigint): Promise<Note | null>;
    getNotes(): Promise<Array<Note>>;
    getProfile(): Promise<Profile | null>;
    getPublication(id: bigint): Promise<Publication | null>;
    getPublications(): Promise<Array<Publication>>;
    getResearchProject(id: bigint): Promise<ResearchProject | null>;
    getResearchProjects(): Promise<Array<ResearchProject>>;
    submitContact(submission: ContactSubmission): Promise<Result>;
}
import type { Article as _Article, ArticleInput as _ArticleInput, ContactRecord as _ContactRecord, Note as _Note, NoteInput as _NoteInput, Profile as _Profile, Publication as _Publication, PublicationInput as _PublicationInput, ResearchInput as _ResearchInput, ResearchProject as _ResearchProject, Result as _Result, Token as _Token } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async adminChangePassword(arg0: Token, arg1: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.adminChangePassword(arg0, arg1);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminChangePassword(arg0, arg1);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminCreateArticle(arg0: Token, arg1: ArticleInput): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateArticle(arg0, to_candid_ArticleInput_n3(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateArticle(arg0, to_candid_ArticleInput_n3(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminCreateNote(arg0: Token, arg1: NoteInput): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateNote(arg0, to_candid_NoteInput_n5(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateNote(arg0, to_candid_NoteInput_n5(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminCreatePublication(arg0: Token, arg1: PublicationInput): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreatePublication(arg0, to_candid_PublicationInput_n7(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreatePublication(arg0, to_candid_PublicationInput_n7(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminCreateResearch(arg0: Token, arg1: ResearchInput): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateResearch(arg0, to_candid_ResearchInput_n9(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateResearch(arg0, to_candid_ResearchInput_n9(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminDeleteArticle(arg0: Token, arg1: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteArticle(arg0, arg1);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteArticle(arg0, arg1);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminDeleteNote(arg0: Token, arg1: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteNote(arg0, arg1);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteNote(arg0, arg1);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminDeletePublication(arg0: Token, arg1: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeletePublication(arg0, arg1);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeletePublication(arg0, arg1);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminDeleteResearch(arg0: Token, arg1: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteResearch(arg0, arg1);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteResearch(arg0, arg1);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetContacts(arg0: Token): Promise<{
        __kind__: "ok";
        ok: Array<ContactRecord>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetContacts(arg0);
                return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetContacts(arg0);
            return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminLogin(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: Token;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0, arg1);
                return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0, arg1);
            return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminLogout(arg0: Token): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogout(arg0);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogout(arg0);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateArticle(arg0: Token, arg1: bigint, arg2: ArticleInput): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateArticle(arg0, arg1, to_candid_ArticleInput_n3(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateArticle(arg0, arg1, to_candid_ArticleInput_n3(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateNote(arg0: Token, arg1: bigint, arg2: NoteInput): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateNote(arg0, arg1, to_candid_NoteInput_n5(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateNote(arg0, arg1, to_candid_NoteInput_n5(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateProfile(arg0: Token, arg1: ProfileInput): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateProfile(arg0, arg1);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateProfile(arg0, arg1);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdatePublication(arg0: Token, arg1: bigint, arg2: PublicationInput): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdatePublication(arg0, arg1, to_candid_PublicationInput_n7(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdatePublication(arg0, arg1, to_candid_PublicationInput_n7(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateResearch(arg0: Token, arg1: bigint, arg2: ResearchInput): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateResearch(arg0, arg1, to_candid_ResearchInput_n9(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateResearch(arg0, arg1, to_candid_ResearchInput_n9(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminValidateToken(arg0: Token): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminValidateToken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminValidateToken(arg0);
            return result;
        }
    }
    async getArticle(arg0: bigint): Promise<Article | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticle(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticle(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getArticles(): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticles();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticles();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNote(arg0: bigint): Promise<Note | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNote(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNote(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotes(): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotes();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotes();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublication(arg0: bigint): Promise<Publication | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublication(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublication(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublications(): Promise<Array<Publication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublications();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublications();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResearchProject(arg0: bigint): Promise<ResearchProject | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getResearchProject(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResearchProject(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResearchProjects(): Promise<Array<ResearchProject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResearchProjects();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResearchProjects();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitContact(arg0: ContactSubmission): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContact(arg0);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContact(arg0);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Article_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Article): Article {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Note_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Note): Note {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Publication_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Publication): Publication {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_ResearchProject_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResearchProject): ResearchProject {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Article]): Article | null {
    return value.length === 0 ? null : from_candid_Article_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Note]): Note | null {
    return value.length === 0 ? null : from_candid_Note_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Profile]): Profile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Publication]): Publication | null {
    return value.length === 0 ? null : from_candid_Publication_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ResearchProject]): ResearchProject | null {
    return value.length === 0 ? null : from_candid_ResearchProject_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    content: string;
    publishDate: string;
    coverImage: string;
    pdfUrl: [] | [string];
    excerpt: string;
    category: string;
}): {
    id: bigint;
    title: string;
    content: string;
    publishDate: string;
    coverImage: string;
    pdfUrl?: string;
    excerpt: string;
    category: string;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        publishDate: value.publishDate,
        coverImage: value.coverImage,
        pdfUrl: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.pdfUrl)),
        excerpt: value.excerpt,
        category: value.category
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    content: string;
    publishDate: string;
    tags: Array<string>;
    pdfUrl: [] | [string];
    excerpt: string;
}): {
    id: bigint;
    title: string;
    content: string;
    publishDate: string;
    tags: Array<string>;
    pdfUrl?: string;
    excerpt: string;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        publishDate: value.publishDate,
        tags: value.tags,
        pdfUrl: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.pdfUrl)),
        excerpt: value.excerpt
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    venue: string;
    link: string;
    year: bigint;
    authors: Array<string>;
    pubType: string;
    pdfUrl: [] | [string];
}): {
    id: bigint;
    title: string;
    venue: string;
    link: string;
    year: bigint;
    authors: Array<string>;
    pubType: string;
    pdfUrl?: string;
} {
    return {
        id: value.id,
        title: value.title,
        venue: value.venue,
        link: value.link,
        year: value.year,
        authors: value.authors,
        pubType: value.pubType,
        pdfUrl: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.pdfUrl))
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    fullContent: string;
    tags: Array<string>;
    description: string;
    seqNum: bigint;
    imageUrl: string;
    pdfUrl: [] | [string];
}): {
    id: bigint;
    title: string;
    fullContent: string;
    tags: Array<string>;
    description: string;
    seqNum: bigint;
    imageUrl: string;
    pdfUrl?: string;
} {
    return {
        id: value.id,
        title: value.title,
        fullContent: value.fullContent,
        tags: value.tags,
        description: value.description,
        seqNum: value.seqNum,
        imageUrl: value.imageUrl,
        pdfUrl: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.pdfUrl))
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_ContactRecord>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<ContactRecord>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Token;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Token;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Article>): Array<Article> {
    return value.map((x)=>from_candid_Article_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Note>): Array<Note> {
    return value.map((x)=>from_candid_Note_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Publication>): Array<Publication> {
    return value.map((x)=>from_candid_Publication_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ResearchProject>): Array<ResearchProject> {
    return value.map((x)=>from_candid_ResearchProject_n28(_uploadFile, _downloadFile, x));
}
function to_candid_ArticleInput_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ArticleInput): _ArticleInput {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_NoteInput_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NoteInput): _NoteInput {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_PublicationInput_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PublicationInput): _PublicationInput {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_ResearchInput_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResearchInput): _ResearchInput {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    fullContent: string;
    tags: Array<string>;
    description: string;
    seqNum: bigint;
    imageUrl: string;
    pdfUrl?: string;
}): {
    title: string;
    fullContent: string;
    tags: Array<string>;
    description: string;
    seqNum: bigint;
    imageUrl: string;
    pdfUrl: [] | [string];
} {
    return {
        title: value.title,
        fullContent: value.fullContent,
        tags: value.tags,
        description: value.description,
        seqNum: value.seqNum,
        imageUrl: value.imageUrl,
        pdfUrl: value.pdfUrl ? candid_some(value.pdfUrl) : candid_none()
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    content: string;
    publishDate: string;
    coverImage: string;
    pdfUrl?: string;
    excerpt: string;
    category: string;
}): {
    title: string;
    content: string;
    publishDate: string;
    coverImage: string;
    pdfUrl: [] | [string];
    excerpt: string;
    category: string;
} {
    return {
        title: value.title,
        content: value.content,
        publishDate: value.publishDate,
        coverImage: value.coverImage,
        pdfUrl: value.pdfUrl ? candid_some(value.pdfUrl) : candid_none(),
        excerpt: value.excerpt,
        category: value.category
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    content: string;
    publishDate: string;
    tags: Array<string>;
    pdfUrl?: string;
    excerpt: string;
}): {
    title: string;
    content: string;
    publishDate: string;
    tags: Array<string>;
    pdfUrl: [] | [string];
    excerpt: string;
} {
    return {
        title: value.title,
        content: value.content,
        publishDate: value.publishDate,
        tags: value.tags,
        pdfUrl: value.pdfUrl ? candid_some(value.pdfUrl) : candid_none(),
        excerpt: value.excerpt
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    venue: string;
    link: string;
    year: bigint;
    authors: Array<string>;
    pubType: string;
    pdfUrl?: string;
}): {
    title: string;
    venue: string;
    link: string;
    year: bigint;
    authors: Array<string>;
    pubType: string;
    pdfUrl: [] | [string];
} {
    return {
        title: value.title,
        venue: value.venue,
        link: value.link,
        year: value.year,
        authors: value.authors,
        pubType: value.pubType,
        pdfUrl: value.pdfUrl ? candid_some(value.pdfUrl) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
